unit uGemRegel42Returnering.types;

interface
const
  // Ordre types
  ORDRETYPE_NORMAL = 1;
  ORDRETYPE_RETUR = 2;

  // Recept status
  RECEPTSTATUS_MANUAL = 0;
  RECEPTSTATUS_CREDIT_UNDONE = 4;

  // Ordre status
  ORDRESTATUS_TAKSERET = 1;
  ORDRESTATUS_AFSLUTTET = 2;

  // DK Types
  DKTYPE_SYGEHJAELP = 1;
  DKTYPE_EGENBETALING = 2;

  // Logging/Result states
  STEP_INIT = 100;
  STEP_EDIT_RCP_OPLYS = 101;
  STEP_RCP_OPLYS_POST = 102;
  STEP_INSERT_EKSP = 110;
  STEP_INSERT_EKSP_POST = 111;
  STEP_EDIT_OLD_EKSP = 113;
  STEP_EDIT_OLD_EKSP_POST = 114;
  STEP_INSERT_EKSPLIN_SALG = 120;
  STEP_INSERT_EKSPLIN_SALG_POST = 121;
  STEP_INSERT_EKSPLIN_TILSKUD = 130;
  STEP_INSERT_EKSPLIN_TILSKUD_POST = 131;
  STEP_INSERT_ETIKET = 140;
  STEP_INSERT_ETIKET_POST = 141;
  STEP_EDIT_TILSKUD = 150;
  STEP_EDIT_TILSKUD_POST = 151;

  // Tilskud regler (range check)
  REGLER_SYGDOM_LOW = 41;
  REGLER_SYGDOM_HIGH = 43;

  // Misc
  FIRST_LINE_NR = 1;
  DEFAULT_PAKKE_NR = 0;
  ROUNDING_INCREMENT = 5;

implementation

end.
